version: 2

workflows:
  version: 2
  main:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v1-yarn-cache-{{ checksum "package.json" }}-
            - v1-yarn-cache-
      - run: yarn
      - save_cache:
          key: v1-yarn-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run: yarn test
