version: 2.1

workflows:
  main:
    jobs:
      - test
      - check-types

jobs:
  check-types:
    executor: node
    steps:
      - yarn:
          run: check:types
  test:
    executor: node
    steps:
      - yarn:
          run: test:ci

commands:
  yarn:
    parameters:
      run:
        type: string
    steps:
      - checkout
      - install_deps
      - run: yarn run <<parameters.run>>
  install_deps:
    parameters:
      cache-version:
        type: string
        default: v1
    steps:
      - restore_cache:
          keys:
            - <<parameters.cache-version>>-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: <<parameters.cache-version>>-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

executors:
  node:
    docker:
      - image: circleci/node:10
